
server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.94.202:8761//eureka

spring:
  cloud:
    config:
      enabled: false
    compatibility-verifier:
      enabled: false

  application:
    name: apigateway-service