name: gateway-server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: build and release to DockerHub 
      env:
        NAME: bes99 # 계정 명
        REPO: gateway-server # 레포 이름
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest
        
  # deploy:
  #   needs: build
  #   name: Deploy
  #   runs-on: [ self-hosted ]
  #   steps:
  #     - name: Docker run
  #       run: |
  #             sudo docker ps -q --filter "name=euro-planner" | grep -q . && sudo docker stop "euro-planner" && sudo docker rmi  "euics/euro-planner"
  #             sudo docker run -d --name euro-planner --rm -p 8080:8080 euics/euro-planner
